# Generated by Django 3.2.23 on 2024-06-03 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='marks',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marks1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marks2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marks3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marks4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marks5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='mobile',
            field=models.BigIntegerField(default=1000000000),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
