# Generated by Django 3.2.23 on 2024-06-03 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smsapp', '0002_auto_20240603_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='rno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentmodel',
            unique_together={('rno', 'user')},
        ),
    ]
