# Generated by Django 3.2.23 on 2024-06-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_auto_20240603_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='rno',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='studentmodel',
            unique_together=set(),
        ),
    ]
